package project.tdlogistics.orders.entities;

public enum Role {
    CUSTOMER,
    ADMIN,
    MANAGER,
    HUMAN_RESOURCE_MANAGER,
    TELLER,
    COMPLAINTS_SOLVER,
    AGENCY_MANAGER,
    AGENCY_HUMAN_RESOURCE_MANAGER,
    AGENCY_TELLER,
    AGENCY_COMPLAINTS_SOLVER,
    SHIPPER,
    DRIVER,
    TRANSPORT_PARTNER_REPRESENTOR,
    BUSINESS
}

