POST http://localhost:8762/v2/auth/login
Content-Type: application/json

{
    "username": "minhluxuan2k4",
    "password": "MinhLuXuan@2k4"
}

###

POST http://localhost:8081/v2/auth/otp/send
Content-Type: application/json

{
    "phoneNumber": "0981430418",
    "email": "minhfaptv@gmail.com"
}

###

POST http://localhost:8081/v2/auth/otp/verify
Content-Type: application/json

{
    "email": "minhfaptv@gmail.com",
    "phoneNumber": "0981430418",
    "otp": "5875"
}