package project.tdlogistics.users.entities;

public enum Role {
    CUSTOMER,
    ADMIN,
    MANAGER,
    HUMAN_RESOURCE_MANAGER,
    TELLER,
    COMPLAINTS_SOLVER,
    AGENCY_MANAGER,
    AGENCY_HUMAN_RESOURCE_MANAGER,
    AGENCY_TELLER,
    AGENCY_COMPLAINTS_SOLVER,
    SHIPPER,
    DRIVER
}
