package project.tdlogistics.vehicle.entities;

public enum Role {
    TRANSPORT_PARTNER_REPRESENTOR, PARTNER_SHIPPER, PARTNER_DRIVER, AGENCY_SHIPPER, AGENCY_DRIVER, DRIVER, CUSTOMER, ADMIN, MANAGER, HUMAN_RESOURCE_MANAGER, TELLER, COMPLAINTS_SOLVER, AGENCY_MANAGER, AGENCY_HUMAN_RESOURCE_MANAGER, AGENCY_TELLER, AGENCY_COMPLAINTS_SOLVER, SHIPPER
}